spring:
  application:
    name: cloud-movie-biz1-local
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        
  datasource:
    initialize: true
    platform: h2
    url: jdbc:h2:mem:testdb;
    username: sa
    password: null
  session:
    store-type: hash-map
#  redis:
#    host: 169.56.68.108
#    port: 7777
#    password: redis1234
#    sentinel:
#      master: mymaster
#      nodes: 169.56.68.114:16379,169.56.68.119:16379,169.56.66.35:16379
      

server:
  port: 8080
    
logging:
  level:
    root: INFO
    com.skcc: TRACE
    org.springframework.data.redis: INFO