spring:
  application:
    name: cloud-movie-localhost
  h2:
    console:
      enabled: true
  datasource:
    initialize: true
    platform: h2
    url: jdbc:h2:mem:testdb;
    username: sa
    password: null
  session:
    store-type: hash-map
    
server:
  port: 80
    
logging:
  level:
    root: INFO
    com.skcc: TRACE